### ISSUE TITLE
ex2: pep8: Inline comments should be separated by at least two spaces from the statement

### ISSUE THREAD

**Issue by todd-dsm** [zedshaw/learn-python3-thw-code#2]
In Exercise 2, pep8 suggests the [inline-comment] _should_ have 2 spaces between the statement and the octothorpe. 

A very small but, apparently, important distinction according to the pep. It's worth noting that even with 1 space the program works as described. 

[inline-comment]:https://www.python.org/dev/peps/pep-0008/#inline-comments

**Comment by zedshaw** [comment]
Cool, sort of a weird requirement but I'll change it.
