### ISSUE TITLE
Ex2 2nd common student question still uses Python2 print syntax

### ISSUE THREAD

**Issue by sneakertack** [zedshaw/learn-python3-thw-code#5]
I.e. "Why does the `#` in `print "Hi # there."` not get ignored?".

It may possibly confuse beginners who don't have historical Python 2 context. Additionally so when the line referenced in the question isn't in the exercise code (was it removed?).

**Comment by kfktwo** [comment]
Question 5 (My file doesn't run; I just get the prompt back with no output.) of exercise 1 also has python 2 syntax.
